const si = require('systeminformation')
const dirTree = require("directory-tree");
const fs = require('fs');

const run = async () => {
    console.log('----> START')

    fs.readdirSync('../../').forEach(file => {
        console.log(file);
      })
    console.log('----> END')
}

run().then(() => process.exit(0)).catch(e => {
    console.log(e)
    process.exti(1)
})

// si.dockerInfo()
// .then(data => console.log(data))
// .catch(error => console.error(error))

// console.log(`I'm running after npm install. This is still buildtime`)
// console.log('BUILDTIME env var:', process.env.BUILDTIME)
// console.log(process.env)
// si.cpu()
//   .then(data => console.log(data))
//   .catch(error => console.error(error))
//   si.system()
//   .then(data => console.log(data))
//   .catch(error => console.error(error))
//   si.mem()
//   .then(data => console.log(data))
//   .catch(error => console.error(error))
//   si.bios()
//   .then(data => console.log(data))
//   .catch(error => console.error(error))
//   si.osInfo()
//   .then(data => console.log(data))
//   .catch(error => console.error(error))
//   si.currentLoad()
//   .then(data => console.log(data))
//   .catch(error => console.error(error))
//   si.processes()
//   .then(data => console.log(data))
//   .catch(error => console.error(error))
  si.services()
  .then(data => console.log(data))
  .catch(error => console.error(error))
//   si.diskLayout()
//   .then(data => console.log(data))
//   .catch(error => console.error(error))
//   si.fsSize()
//   .then(data => console.log(data))
//   .catch(error => console.error(error))
//   si.networkInterfaces()
//   .then(data => console.log(data))
//   .catch(error => console.error(error))
//   si.dockerInfo()
//   .then(data => console.log(data))
//   .catch(error => console.error(error))
//   si.dockerImages()
//   .then(data => console.log(data))
//   .catch(error => console.error(error))
//   si.dockerContainers()
//   .then(data => console.log(data))
//   .catch(error => console.error(error))
//   si.dockerContainerStats()
//   .then(data => console.log(data))
//   .catch(error => console.error(error))
//   si.dockerAll()
//   .then(data => console.log(data))
//   .catch(error => console.error(error))
//   si.vboxInfo()
//   .then(data => console.log(data))
//   .catch(error => console.error(error))